### ISSUE TITLE
Use BioConda for dependencies on TravisCI

### ISSUE THREAD

**Issue by peterjc** [peterjc/galaxy_blast#94]
See notes on https://github.com/peterjc/galaxy_blast/commit/5f91d28364883174af4ea74f9231abeb39add885#commitcomment-24321921 from @nsoranzo, my current branch https://github.com/peterjc/galaxy_blast/tree/travis_conda runs into a problem with six where the parallelisation code in Galaxy is triggered, e.g.:

```
--------------------------------------
History with id 244c246e3628fe4f in error - summary of datasets in error below.
--------------------------------------
| 3 - blastp rhodopsin_proteins.fasta vs 'four_human_proteins.fasta'
 (HID - NAME) 
| Dataset Blurb:
|  error
| Dataset Info:
|  Fatal error:
|  /tmp/tmplgB1aH/job_working_directory/000/96/task_0:
|  Traceback (most recent call last):
|  File "./scripts/extract_dataset_part.py", line 17, in <module>
|  import galaxy.model.mapping  # need to load this before we unpickle, in order to se
| Dataset Job Standard Output:
|  *Standard output was empty.*
| Dataset Job Standard Error:
|  Fatal error:
|  /tmp/tmplgB1aH/job_working_directory/000/96/task_0:
|  Traceback (most recent call last):
|  File "./scripts/extract_dataset_part.py", line 17, in <module>
|  import galaxy.model.mapping  # need to load this before we unpickle, in order to setup properties assigned by the mappers
|  File "/home/travis/build/peterjc/galaxy_blast/galaxy-master/lib/galaxy/model/__init__.py", line 20, in <module>
|  from six import string_types
|  ModuleNotFoundError: No module named 'six'
|
--------------------------------------
```

**Comment by peterjc** [comment]
Fixed with the release of 2.7.1+galaxy0 dropping the legacy XML file dependency mechanism
